trigger:
- main

variables:
  dockerRegistryServiceConnection: 'cd711fb4-6f1e-40db-b70a-ad286cc28597'
  imageRepository: 'akvcreatektetrisgameapp'
  containerRegistry: 'arbazacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # If you're using a self-hosted agent, replace this with your agent pool name
  selfHostedPoolName: 'Azure Pipelines'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Job
    pool:
      name: $(selfHostedPoolName)  # Use your actual self-hosted agent pool name
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push Docker Image to ACR
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
